### ISSUE TITLE
ItemSpawner does nothing yet

### ISSUE THREAD

**Issue by JakeDaBoss** [JakeDaBoss/PhaseFour#3]
Needs to be correctly set-up.

**Comment by roachy** [comment]
Being worked on, I'm adding item types for weapon spawns and other items.

**Comment by JakeDaBoss** [comment]
Check my recent commit.  Needs to be added in the actual item file.

**Comment by JakeDaBoss** [comment]
Nevermind. I see you got that figured out.

**Comment by JakeDaBoss** [comment]
Next revision pushed. Uploading code now, will return a message shortly on fixed or not.

**Comment by JakeDaBoss** [comment]
Works properly.
